# Generated by Django 4.0.2 on 2023-08-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='ip')),
                ('port', models.IntegerField(verbose_name='port')),
                ('character', models.CharField(blank=True, max_length=32, null=True, verbose_name='character')),
                ('is_connected', models.BooleanField(default=False, verbose_name='is connected')),
            ],
        ),
        migrations.CreateModel(
            name='Odor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odor', models.CharField(max_length=32, verbose_name='odor')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(max_length=16, verbose_name='角色名')),
                ('create_date', models.DateTimeField(verbose_name='创建时间')),
                ('update_date', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=32, verbose_name='event_name')),
                ('role_num', models.SmallIntegerField(default=1, verbose_name='')),
                ('time_window', models.SmallIntegerField(default=10, verbose_name='')),
                ('port', models.SmallIntegerField(choices=[(1, 'Port 1'), (2, 'Port 2'), (3, 'Port 3'), (4, 'Port 4')], default=1, verbose_name='')),
                ('duration', models.SmallIntegerField(default=3, verbose_name='')),
                ('pwm', models.IntegerField(default=150, verbose_name='')),
                ('uuid', models.CharField(default=None, max_length=36, verbose_name='')),
                ('input_device', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='FriendList_input_device', to='web.role', verbose_name='')),
                ('output_device', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='FriendList_output_device', to='web.role', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='RoleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_selection', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='FriendList_role_selection', to='web.role', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='OdorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odor_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendList_odor_selection', to='web.odor', verbose_name='')),
            ],
        ),
    ]
